# Generated by Django 5.1.6 on 2025-06-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_delete_timetableentry'),
    ]

    operations = [
    ]
